import React from "react";

type Props = {
  title: string;
  header?: string;
  footer?: string;
  children: React.ReactNode;
};

export default function PrintLayout({ title, header, footer, children }: Props) {
  return (
    <div className="p-6">
      <style
        // print scaffolding
        dangerouslySetInnerHTML={{
          __html: `
        @media print {
          .rapid-print-header, .rapid-print-footer { position: fixed; width: 100%; left: 0; right: 0; color: #444; font-size: 10px; }
          .rapid-print-header { top: 0; border-bottom: 1px solid #ddd; padding: 4px 8px;}
          .rapid-print-footer { bottom: 0; border-top: 1px solid #ddd; padding: 4px 8px;}
          body { margin-top: 32px; margin-bottom: 32px; }
        }`
        }}
      />
      <div className="rapid-print-header">{header || "Rapid"}</div>
      <div className="rapid-print-footer">{footer || "Generated by Rapid"}</div>
      <header className="mb-6">
        <h1 className="text-xl font-semibold">{title}</h1>
      </header>
      <main>{children}</main>
    </div>
  );
}